Release 2.1.3
PrestaShop/ps_wirepayment pull request #75
Opened 2022-05-04 09:09 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.1.2
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release test

### Version 2.1.3 content

https://github.com/PrestaShop/ps_wirepayment/pull/74 Bump version to 2.1.3
https://github.com/PrestaShop/ps_wirepayment/pull/73 Fix deprecated message with PHP 8.1

2022-05-04 16:02 UTC, matks approved these changes, later dismissed

2022-05-18 12:16 UTC, florine2623 requested changes
Hello @atomiix ,

I have an issue with this PR.
The version is not correct :
<img width="988" alt="Screenshot 2022-05-18 at 14 11 50" src="https://user-images.githubusercontent.com/16019289/169036537-2bc80426-df3c-40cc-94bc-0541258f6303.png">

When I try to upgrade I have an error.
- On docker, PHP 8 : 
<img width="844" alt="Screenshot 2022-05-18 at 14 11 00" src="https://user-images.githubusercontent.com/16019289/169036483-85bed659-ef42-412a-8050-1b42d3f0bc79.png">

- With mamp, php 7.4 :
<img width="773" alt="Screenshot 2022-05-18 at 14 14 38" src="https://user-images.githubusercontent.com/16019289/169036448-013d930d-e860-41a4-86a0-2d02af51e2a6.png">

Could you check please ?
Thanks!

2022-05-18 13:48 UTC, atomiix commented
@florine2623 I think this bug doesn't come from the module but from the API distribution/apidistributionclient module and even maybe Github as it seems that the connexion timed out.

2022-05-19 15:10 UTC, florine2623 approved these changes
Hello @atomiix ,

Thanks for the PR !

_Tested on 1.7.8.x branch - PHP 7.3_
Upgrade to work well v2.1.3 :white_check_mark:
<img width="463" alt="Screenshot 2022-05-19 at 16 41 30" src="https://user-images.githubusercontent.com/16019289/169329406-f5c20d5a-fb09-4f26-845a-08cd4c4c10ef.png">

Tested basic feature of the module :white_check_mark:


_Tested on develop - PHP 8.0 - disabled ps_distributionapiclient_
<img width="426" alt="Screenshot 2022-05-19 at 17 09 36" src="https://user-images.githubusercontent.com/16019289/169329877-b26fe1b2-b84f-4829-9a7e-516a35ab5da6.png">

It is looking good and QA ✅ !
Thanks!

2022-05-19 15:13 UTC, merged

2022-05-19 15:13 UTC, atomiix commented
Thanks @florine2623 !